// Production database configuration. Use only the public anon key in a browser.
// The app never persists data in browser storage.
const SUPABASE_URL = "https://qpsglpeuuvimtvyljtma.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_cV28IR4s0MCaYP2b5FYBhg_hBmjLO3E";
const TABLES = { workers: "workers", attendance: "attendances", advances: "advances", expenses: "expenses", payments: "payments" };
const $ = (id) => document.getElementById(id);
const state = { db: null, workers: [], attendances: [], advances: [], expenses: [], payments: [], view: "workers" };
const today = () => new Date().toISOString().slice(0, 10);
const money = (n) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(n) || 0);
const initials = (name) => name.split(/\s+/).slice(0, 2).map((x) => x[0]).join("").toUpperCase();
const esc = (text = "") => String(text).replace(/[&<>"]/g, (x) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" })[x]);
function toast(text) { const node = $("toast"); node.textContent = text; node.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => node.classList.remove("show"), 2800); }
function status(text, error = false) { $("sync-status").textContent = text; $("sync-status").classList.toggle("error", error); }
function records(workerId) { return { attendance: state.attendances.filter((x) => x.worker_id === workerId), advances: state.advances.filter((x) => x.worker_id === workerId), expenses: state.expenses.filter((x) => x.worker_id === workerId), payments: state.payments.filter((x) => x.worker_id === workerId) }; }
function totals(workerId) { const w = state.workers.find((x) => x.id === workerId); if (!w) return { earned: 0, adv: 0, exp: 0, paid: 0, balance: 0, full: 0, half: 0 }; const r = records(workerId), full = r.attendance.filter((x) => x.status === "P").length, half = r.attendance.filter((x) => x.status === "H").length; const sum = (items) => items.reduce((a, x) => a + Number(x.amount || 0), 0); const earned = Number(w.wage) * (full + half / 2), adv = sum(r.advances), exp = sum(r.expenses), paid = sum(r.payments); return { earned, adv, exp, paid, balance: earned - adv - exp - paid, full, half }; }
function workerCard(w, mode = "workers") { const t = totals(w.id); const actions = mode === "attendance" ? `<div class="attendance-actions">${["P","H","A"].map((s) => `<button data-attendance="${w.id}" data-status="${s}" class="${state.attendances.find((a) => a.worker_id === w.id && a.date === $("attendance-date").value)?.status === s ? "selected" : ""}">${s}</button>`).join("")}</div>` : `<div class="row-actions"><button data-detail="${w.id}" title="Full history">◷</button><button data-edit="${w.id}" title="Edit">✎</button><button data-delete="${w.id}" title="Delete">×</button></div>`; const quick = mode === "dashboard" ? `<div class="quick-actions"><button data-transaction="${w.id}" data-type="advances">+ Advance</button><button data-transaction="${w.id}" data-type="expenses">+ Expense</button><button data-transaction="${w.id}" data-type="payments">+ Pay</button></div>` : ""; return `<article class="${mode === "attendance" ? "worker-row" : "balance-row"}"><div class="person"><span class="avatar">${esc(initials(w.name))}</span><div><h3>${esc(w.name)}</h3><p>${esc(w.skill || "General")} · ${money(w.wage)}/day</p>${quick}</div></div>${mode === "dashboard" ? `<div class="balance"><strong>${money(t.balance)}</strong><span>${t.balance >= 0 ? "To pay" : "Extra paid"}</span></div>` : actions}</article>`; }
function renderDashboard() { const all = state.workers.map((w) => totals(w.id)), present = state.attendances.filter((x) => x.date === today() && ["P","H"].includes(x.status)).length; $("today-label").textContent = new Intl.DateTimeFormat("en-IN", { dateStyle: "full" }).format(new Date()); $("stat-workers").textContent = state.workers.length; $("stat-present").textContent = present; $("stat-payable").textContent = money(all.reduce((a, x) => a + Math.max(0, x.balance), 0)); const month = today().slice(0, 7); $("stat-earned").textContent = money(state.workers.reduce((sum, w) => sum + state.attendances.filter((a) => a.worker_id === w.id && a.date.startsWith(month)).reduce((n, a) => n + Number(w.wage) * (a.status === "P" ? 1 : a.status === "H" ? .5 : 0), 0), 0)); $("balance-list").innerHTML = state.workers.length ? state.workers.map((w) => workerCard(w, "dashboard")).join("") : empty("No workers yet"); }
function renderAttendance() { const q = $("attendance-search").value.toLowerCase(); const list = state.workers.filter((w) => `${w.name} ${w.phone || ""}`.toLowerCase().includes(q)); $("attendance-list").innerHTML = list.length ? list.map((w) => workerCard(w, "attendance")).join("") : empty("No matching workers"); }
function historyRows(items, type) { return items.map((x) => { const w = state.workers.find((y) => y.id === x.worker_id); return `<div class="history-row"><div><strong>${esc(w?.name || "Deleted worker")}</strong><p>${esc(x.date)} · ${esc(x.note || x.status || "—")}</p></div><strong>${type === "Attendance" ? esc(x.status) : money(x.amount)}</strong></div>`; }).join(""); }
function renderHistory() { const worker = $("history-worker").value, month = $("history-month").value, pick = (items) => items.filter((x) => (worker === "all" || x.worker_id === worker) && (!month || x.date.startsWith(month))).sort((a,b) => b.date.localeCompare(a.date)); const groups = [["Attendance", pick(state.attendances)], ["Advances", pick(state.advances)], ["Expenses", pick(state.expenses)], ["Payments", pick(state.payments)]]; $("history-list").innerHTML = groups.map(([name, items]) => `<article class="history-card"><h3>${name} <span class="muted">(${items.length})</span></h3>${items.length ? historyRows(items, name) : `<div class="history-row muted">No records</div>`}</article>`).join(""); }
function renderWorkers() { const q = $("worker-search").value.toLowerCase(), items = state.workers.filter((w) => `${w.name} ${w.phone || ""} ${w.skill || ""}`.toLowerCase().includes(q)); $("worker-list").innerHTML = items.length ? items.map((w) => workerCard(w)).join("") : empty(state.workers.length ? "No matching workers" : "No workers yet. Add your first worker."); }
function empty(text) { return `<div class="empty">${text}</div>`; }
function render() { renderDashboard(); renderAttendance(); renderHistory(); renderWorkers(); const select = $("history-worker"), selected = select.value; select.innerHTML = `<option value="all">All workers</option>${state.workers.map((w) => `<option value="${w.id}">${esc(w.name)}</option>`).join("")}`; select.value = [...select.options].some((x) => x.value === selected) ? selected : "all"; }
async function load() { const names = Object.entries(TABLES); const result = await Promise.all(names.map(async ([key, table]) => { const { data, error } = await state.db.from(table).select("*"); if (error) throw new Error(`${table}: ${error.message}`); state[key] = data || []; })); render(); return result; }
function showView(name) { state.view = name; document.querySelectorAll(".view").forEach((x) => x.classList.toggle("hidden", x.id !== `${name}-view`)); document.querySelectorAll(".nav-item").forEach((x) => x.classList.toggle("active", x.dataset.view === name)); $("page-title").textContent = ({ dashboard:"Dashboard", attendance:"Attendance", history:"History", workers:"Workers" })[name]; $("export-button").style.visibility = name === "dashboard" ? "visible" : "hidden"; }
function openWorker(worker) { $("worker-form").reset(); $("worker-id").value = worker?.id || ""; $("worker-modal-title").textContent = worker ? "Edit worker" : "Add worker"; $("worker-name").value = worker?.name || ""; $("worker-phone").value = worker?.phone || ""; $("worker-wage").value = worker?.wage || ""; $("worker-skill").value = worker?.skill || "Flooring"; $("worker-joining").value = worker?.joining_date || today(); $("worker-modal").showModal(); }
function openTransaction(workerId, type) { $("transaction-form").reset(); $("transaction-worker-id").value = workerId; $("transaction-type").value = type; $("transaction-title").textContent = `Add ${type.slice(0, -1)}`; $("transaction-date").value = $("attendance-date").value || today(); $("transaction-modal").showModal(); }
function openDetail(id) { const w = state.workers.find((x) => x.id === id), t = totals(id), r = records(id); if (!w) return; $("detail-name").textContent = w.name; $("detail-meta").textContent = `${w.phone || "No phone"} · ${w.skill || "General"} · ${money(w.wage)}/day`; $("detail-summary").innerHTML = [["Earned",t.earned],["Advance",t.adv],["Expense",t.exp],["Balance",t.balance]].map(([n,v]) => `<article><span>${n}</span><strong>${money(v)}</strong></article>`).join(""); $("detail-history").innerHTML = [["Attendance",r.attendance],["Advances",r.advances],["Expenses",r.expenses],["Payments",r.payments]].map(([n,x]) => `<article class="history-card"><h3>${n}</h3>${x.length ? historyRows(x,n) : `<div class="history-row muted">No records</div>`}</article>`).join(""); $("detail-modal").showModal(); }
async function saveWorker(e) { e.preventDefault(); const id = $("worker-id").value, row = { name: $("worker-name").value.trim(), phone: $("worker-phone").value.trim() || null, wage: Number($("worker-wage").value), skill: $("worker-skill").value, joining_date: $("worker-joining").value || null }; const req = id ? state.db.from(TABLES.workers).update(row).eq("id", id) : state.db.from(TABLES.workers).insert(row); const { error } = await req; if (error) throw error; $("worker-modal").close(); await load(); toast("Worker saved"); }
async function attendance(id, value) { const date = $("attendance-date").value; const current = state.attendances.find((x) => x.worker_id === id && x.date === date); const { error } = current ? await state.db.from(TABLES.attendance).update({ status: value }).eq("id", current.id) : await state.db.from(TABLES.attendance).insert({ worker_id: id, date, status: value }); if (error) throw error; await load(); }
async function start() { $("attendance-date").value = today(); $("transaction-date").value = today(); $("history-month").value = today().slice(0,7); showView("workers"); render(); if (!SUPABASE_URL || !SUPABASE_ANON_KEY) { status("Database credentials are missing", true); toast("Add Supabase credentials to javascript.js"); return; } if (!window.supabase) { status("Database SDK failed to load", true); return; } state.db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }); try { await load(); status("Database connected"); } catch (e) { status(e.message, true); } }
document.querySelectorAll(".nav-item").forEach((x) => x.onclick = () => showView(x.dataset.view)); document.querySelectorAll("[data-close]").forEach((x) => x.onclick = () => $(x.dataset.close).close()); $("add-worker").onclick = () => state.db ? openWorker() : toast("Database is not connected"); $("worker-form").onsubmit = async (e) => { try { await saveWorker(e); } catch (x) { toast(x.message); } }; $("transaction-form").onsubmit = async (e) => { e.preventDefault(); try { const type = $("transaction-type").value, row = { worker_id: $("transaction-worker-id").value, amount: Number($("transaction-amount").value), note: $("transaction-note").value.trim() || null, date: $("transaction-date").value }; const { error } = await state.db.from(TABLES[type]).insert(row); if (error) throw error; $("transaction-modal").close(); await load(); toast("Transaction saved"); } catch (x) { toast(x.message); } }; $("attendance-search").oninput = renderAttendance; $("worker-search").oninput = renderWorkers; $("attendance-date").onchange = renderAttendance; $("history-worker").onchange = renderHistory; $("history-month").onchange = renderHistory; $("mark-all").onclick = async () => { try { for (const w of state.workers.filter((w) => !state.attendances.some((a) => a.worker_id === w.id && a.date === $("attendance-date").value))) await attendance(w.id,"P"); toast("All workers marked present"); } catch (x) { toast(x.message); } }; document.addEventListener("click", async (e) => { try { const d = e.target.dataset; if (d.attendance) await attendance(d.attendance,d.status); if (d.transaction) openTransaction(d.transaction,d.type); if (d.edit) openWorker(state.workers.find((x) => x.id === d.edit)); if (d.detail) openDetail(d.detail); if (d.delete && confirm("Delete this worker and its records?")) { const { error } = await state.db.from(TABLES.workers).delete().eq("id",d.delete); if (error) throw error; await load(); } } catch (x) { toast(x.message); } }); $("export-button").onclick = () => { const csv = [["Name","Phone","Wage","Earned","Advance","Expense","Paid","Balance"],...state.workers.map((w) => { const t=totals(w.id); return [w.name,w.phone,w.wage,t.earned,t.adv,t.exp,t.paid,t.balance]; })].map((x) => x.map((v) => `"${String(v ?? "").replace(/"/g,'""')}"`).join(",")).join("\n"); const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); a.download="floormitra-report.csv"; a.click(); URL.revokeObjectURL(a.href); };
start();
